### ISSUE TITLE
severe decrease in write performance after ~4M rows

### ISSUE THREAD

**Issue by brentp** [dw/py-lmdb#110] opened 2016-04-07 16:18 UTC
I am using lmdb-py version 0.89 on 
`Linux x1 3.16.0-62-generic #83~14.04.1-Ubuntu SMP Fri Feb 26 22:52:39 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

I've created the test-script below to recreate a real scenario where I see a drop in performance with longish (length 44) keys and short values. It's likely this isn't a bug but I didn't see another forum to ask. 
After about 4 million entries, the performance drops from inserting 250K KV pairs in 0.2 seconds to 40 seconds. Am I doing something wrong with the config or the insertion? Or is this to be expected for the keys I'm using?

Here is the output with columns of N-total inserted and time for cursor.putmulti
```
  250000	0.18
  500000	0.23
  750000	0.25
 1000000	0.25
 1250000	0.28
 1500000	0.29
 1750000	0.26
 2000000	0.28
 2250000	0.50
 2500000	0.35
 2750000	0.55
 3000000	0.51
 3250000	0.90
 3500000	1.68
 3750000	1.82
 4000000	4.03
 4250000	3.94
 4500000	16.02
 4750000	17.92
 5000000	41.47
 5250000	45.18
 5500000	40.87
 5750000	70.87
 6000000	41.34
```

and here is the python script:

```Python
import lmdb
import time
import string
import random

CHUNK_SIZE = 250000

env = lmdb.open('ex.lmdb', readonly=False, create=True, map_size=2**31,
                map_async=True, sync=False,
                writemap=True)

txn = env.begin(write=True)

def genpair():

    ri = random.randint
    letters = string.letters
    L = len(letters) - 1
    while True:
        yield "".join(letters[ri(0, L)] for _ in range(44)), "XXXXXX"

chunk = []
for i, p in enumerate(genpair(), start=1):
    chunk.append(p)

    if i % CHUNK_SIZE == 0:
        cursor = txn.cursor()
        t0 = time.time()
        # chunk.sort()
        cursor.putmulti(chunk)
        print "%8d\t%.2f" % (i, time.time() - t0)
        chunk = chunk[:0]
        cursor.close()
```

**Comment by brentp** [comment] 2016-04-07 16:34
With a key size of 14, the slowdown is delayed, but still present:
```
  250000	0.15
  500000	0.21
  750000	0.23
 1000000	0.24
 1250000	0.24
 1500000	0.25
 1750000	0.26
 2000000	0.28
 2250000	0.37
 2500000	0.29
 2750000	0.51
 3000000	0.29
 3250000	0.92
 3500000	1.44
 3750000	0.35
 4000000	0.69
 4250000	2.53
 4500000	1.76
 4750000	0.87
 5000000	0.35
 5250000	2.44
 5500000	3.06
 5750000	4.71
 6000000	3.71
 6250000	3.40
 6500000	3.60
 6750000	5.98
 7000000	9.51
 7250000	5.70
 7500000	8.36
 7750000	10.84
 8000000	25.83
 8250000	41.66
```

**Comment by dw** [comment] 2016-04-07 16:42
I'm still playing, but this looks a lot like memory pressure triggering IO. What does 'free -m' say on the machine? It sounds like Linux might be starting to page out dirty data around the 500mb mark

**Comment by dw** [comment] 2016-04-07 16:43
If that's the case, you may find running with writemap=False much faster as LMDB uses the heap for dirty data in that case (since Linux prioritizes the hotness of anonymous (aka heap) pages over diry pages in file-backed memory), or try using shorter transactions

**Comment by dw** [comment] 2016-04-07 16:47
Just as a final note, be careful, Cursor.put() may be slower than Transaction.put() if the keys you are writing are not localized usefully, and random data is not. For example running your script on PyPy with a simple "for k,v in chunks: txn.put(k, v)" is about 30% here

**Comment by brentp** [comment] 2016-04-07 17:34
thanks for the feedback. using txn directly still doesn't mitigate the slow-down, does it?

**Comment by dw** [comment] 2016-04-07 17:35
txn.put just reduces the algorithmic overhead, it won't fix IO if that's your problem. I was running the script on a 24gb machine with 12gb free and it ran fine well past 4 million keys

**Comment by dw** [comment] 2016-04-07 21:25
Please reopen if problems persist

**Closed by dw** 2016-04-07 21:25 UTC

**Comment by brentp** [comment] 2016-04-07 21:27
It does persist, but perhaps I'm missing the obvious solution... what would I change (beyond transactions which didn't alleviate) in the script to get around the problem?

**Comment by dw** [comment] 2016-04-07 22:43
Hi there,

Try recording 'free -m' output before the run and after the problem appears, also try running 'iostat -x 1' output while the problem is happening, I'm pretty sure iostat (you might have to install the sysstat package to get that command) will show IO pressure.

If it is IO pressure, and writemap=False didn't help, then we just need to figure out what's hogging all the RAM on your machine
